Repository KKewo-Support/KKewo-iOS, pull requests merged in 2025-05, with the labels that each got.

#3 [feat] sound categories
  KKewo-iOS/KKewo-iOS.xcodeproj/project.pbxproj
  KKewo-iOS/KKewo-iOS/Assets.xcassets/soundRecommend.imageset/Contents.json
  KKewo-iOS/KKewo-iOS/Assets.xcassets/soundRecommend.imageset/Image.png
  KKewo-iOS/KKewo-iOS/Model/SelectSoundView.swift
Labels: ✨ Feat

#7 [FEAT] RecommendSountView의 UI를 구현했습니다.
  KKewo-iOS/KKewo-iOS/Assets.xcassets/gray05.colorset/Contents.json
  KKewo-iOS/KKewo-iOS/Assets.xcassets/gray06.colorset/Contents.json
  KKewo-iOS/KKewo-iOS/Feature/RecommendSound/RecommendCategoryButton.swift
  KKewo-iOS/KKewo-iOS/Feature/RecommendSound/RecommendChipsView.swift
  KKewo-iOS/KKewo-iOS/Feature/RecommendSound/RecommendSoundView.swift
  KKewo-iOS/KKewo-iOS/Utilities/Extensions/Array+.swift
Labels: ✨ Feat

#9 [FEAT] MainView의 UI를 구현했습니다.
  KKewo-iOS/KKewo-iOS/Assets.xcassets/mainLogo.imageset/Contents.json
  KKewo-iOS/KKewo-iOS/Assets.xcassets/mainLogo.imageset/mainLogo.svg
  KKewo-iOS/KKewo-iOS/Model/Alarm.swift
  KKewo-iOS/KKewo-iOS/Presentaion/Main/AlarmSetup/View/AlarmSettingView.swift
  KKewo-iOS/KKewo-iOS/Presentaion/Main/AlarmSetup/View/AlarmSetupView.swift
  KKewo-iOS/KKewo-iOS/Presentaion/Main/AlarmSetup/View/DatePickerView.swift
  KKewo-iOS/KKewo-iOS/Presentaion/Main/View/AlarmListView.swift
  KKewo-iOS/KKewo-iOS/Presentaion/Main/View/MainView.swift
  KKewo-iOS/KKewo-iOS/Presentaion/Navigation/CustomNavigationBar.swift
Labels: ✨ Feat

#11 [FEAT] RecommendResultView의 UI를 구현했습니다.
  KKewo-iOS/KKewo-iOS/Assets.xcassets/SampleResult.imageset/Contents.json
  KKewo-iOS/KKewo-iOS/Assets.xcassets/SampleResult.imageset/SampleResult.png
  KKewo-iOS/KKewo-iOS/Assets.xcassets/tail.imageset/Contents.json
  KKewo-iOS/KKewo-iOS/Assets.xcassets/tail.imageset/tail_1x.png
  KKewo-iOS/KKewo-iOS/Assets.xcassets/tailshadow.imageset/Contents.json
  KKewo-iOS/KKewo-iOS/Assets.xcassets/tailshadow.imageset/tailshadow1x.png
  KKewo-iOS/KKewo-iOS/Feature/RecommendResult/RecommendResultView.swift
  KKewo-iOS/KKewo-iOS/Feature/RecommendSound/RecommendSoundView.swift
  KKewo-iOS/KKewo-iOS/Utilities/Components/CustomBorderButton.swift
Labels: ✨ Feat

#13 [Setting] 파일구조 수정했습니다 !
  KKewo-iOS/KKewo-iOS/Feature/AlarmSetup/AlarmSettingView.swift
  KKewo-iOS/KKewo-iOS/Feature/AlarmSetup/AlarmSetupView.swift
  KKewo-iOS/KKewo-iOS/Feature/AlarmSetup/DatePickerView.swift
  KKewo-iOS/KKewo-iOS/Feature/Main/AlarmListView.swift
  KKewo-iOS/KKewo-iOS/Feature/Main/MainView.swift
  KKewo-iOS/KKewo-iOS/Feature/SelectSound/Alarm.swift
  KKewo-iOS/KKewo-iOS/Feature/SelectSound/SelectSoundView.swift
  KKewo-iOS/KKewo-iOS/Feature/SelectSound/SoundList.swift
  KKewo-iOS/KKewo-iOS/Utilities/Components/CustomNavigationBar.swift
  KKewo-iOS/KKewo-iOS/Utilities/Extensions/Font+.swift
Labels: 🪏 Setting

#17 [FIX] 커스텀 버튼의 터치 영역 문제를 수정했습니다
  KKewo-iOS/KKewo-iOS/Utilities/Components/CustomBorderButton.swift
Labels: ⚙️ Fix

#19 [Modify] 횡스크롤 로직 수정했습니다.
  KKewo-iOS/KKewo-iOS/Feature/Onboarding/OnboardingAlarmIntroView.swift
  KKewo-iOS/KKewo-iOS/Feature/Onboarding/OnboardingView.swift
  KKewo-iOS/KKewo-iOS/Feature/Onboarding/OnboardingVoiceIntroView.swift
Labels: ⚒️ Modify
